### ISSUE TITLE
Installation Failure on Windows

### ISSUE THREAD

**Issue by david-f1976** [rundel/parsermd#1]
Tried to install on Windows 7 and R 3.6.2 and fails with a number of errors, mostly --- but not entirely --- related to `R/Library/BH/include/boost/spirit/home/x3/operator/detail/sequence.hpp`.

BH package version is 1.72.0-3.

There is a lot of information put out to the console, so not sure of the best way of showing the information here if you plan to investigate (txt file?)

**Comment by rundel** [comment]
I haven't tried this on windows yet, let me spin up a VM and see what I get. If I can't reproduce I'll let you know.

**Comment by rundel** [comment]
I was just able to install it on a Windows 10 vm with R 4.0.2 and rtools40. I will try with 3.6 but my suspicion is that there is an issue with the older compilers packaged with rtools3.5 supporting the Boost Spirit X3 library which the package depends on for the parser.

**Comment by rundel** [comment]
Yep I am seeing the same failure with Rtools35 - unfortunately the version of gcc bundled is 4.9 which has supports most but not all of the C++14 standard which Boost Spirit X3 relies heavily on. It seems like for windows at least Rtools40 is going to be required (and hence R 4.0). 

@jeroen I'm assume there are no clever hacks around this without upgrading everything?

**Comment by jeroen** [comment]
Not really, the only solution would be to include your own boost headers in the package, instead of using those from BH, and then you can ship an older version of boost that supports C++11.

**Comment by david-f1976** [comment]
> Yep I am seeing the same failure with Rtools35 - unfortunately the version of gcc bundled is 4.9 which has supports most but not all of the C++14 standard which Boost Spirit X3 relies heavily on. It seems like for windows at least Rtools40 is going to be required (and hence R 4.0).
> 
> @jeroen I'm assume there are no clever hacks around this without upgrading everything?

Thanks for the troubleshooting. I will try installing R 4.0 when the opportunity arises and give this another go.

Looking forward to the package's development.
